# Generated by Django 3.1.7 on 2021-05-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(db_column='instructor', on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
    ]
