# Generated by Django 3.1.7 on 2021-05-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210504_2002'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Course',
            field=models.ForeignKey(db_column='Course', default=-10, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
